#!/bin/bash

# Directory to write output to
OUTDIR="../../"

# If we were given an argument, use it as the year for which to pull
# data; otherwise we use the current year
YEAR=`date +%Y`
if [ $# -gt 0 ]
then
     YEAR=$1
fi

./getPredictYearData $YEAR
./predictYear $YEAR
