#!/bin/bash

let NUM_YEARS=5  # Number of years of history to use in predictive model

# Location of Oracle JDBC driver
JDBCJAR="/Applications/SQLWorkbenchj/ojdbc6.jar"

# Directory to write datafiles to
DATADIR="../../Data"
NETDIR="../../Networks"

# If we were given an argument, use it as the year for which to pull
# data; otherwise we use the current year
YEAR=`date +%Y`
if [ $# -gt 0 ]
then
   YEAR=$1
fi

# Pull 3 years of data for historical model files
let START=$YEAR-$NUM_YEARS
let END=$YEAR-1

# Generate the N year historical data for each of the models
for MODEL in fall apply admit
do
   # 5 year historical data
   echo "pulling historical $MODEL from $START to $END..."
   rm -rf ${DATADIR}/${MODEL}_${START}_to_${END}.data 
   java -Xmx512m -cp .:$JDBCJAR ExtractData --$MODEL --from $START --to $END --output ${DATADIR}/${MODEL}_${START}_to_${END}.data 
   echo "building $YEAR $MODEL model for $START to $END..."
   rm -rf ${NETDIR}/${MODEL}_${YEAR}.net
   gfu_net_train ${DATADIR}/${MODEL}_${START}_to_${END}.data ${NETDIR}/${MODEL}_${YEAR}.net 
done
